### ISSUE TITLE
leaving a module and coming back to it remembers old data

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-desktop-wallet#401]
when I am in a section of the wallet and enter tx information, (for instance make a mosaic) and then I leave the module and then come back in it, then it remembers some of the previous information I typed. We should start from scratch each time.

**Comment by NemTechCN** [comment]
fixed

**Comment by decentraliser** [comment]
Not fixed for mosaic amount
![image](https://user-images.githubusercontent.com/36499647/67059783-f20a7d80-f18c-11e9-9908-fdff850f736d.png)
