### ISSUE TITLE
The network type in the top bar should be updated if necessary

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#461]
![image](https://user-images.githubusercontent.com/36499647/67137302-5e58b000-f265-11e9-9028-f17673aa013f.png)

AKA fixing z-index issues with z-index: 99999999999 is often a bad idea

Btw, the dashboard should not even be rendered at this step #172

**Comment by decentraliser** [comment]
AKA fixing z-index issues with z-index: 99999999999 is often a bad idea

**Comment by NemTechCN** [comment]
fixed

**Comment by decentraliser** [comment]
it's not fixed

here is a TEST_NET node, and it still shows MIJIN_TEST
![image](https://user-images.githubusercontent.com/36499647/67387953-6c426400-f5ca-11e9-951c-e2d678626799.png)
