### ISSUE TITLE
Co-signers cannot select to transfer mosaics from multisig accounts

### ISSUE THREAD

**Issue by trestoJP** [nemfoundation/nem2-desktop-wallet#866]
I can select nem.xem but not the another mosaic that created under this multisig account.
mosaic ID : 00B2A35D018CED36

**Comment by decentraliser** [comment]
Thanks for reporting!

For reference
http://explorer.nemtech.network/mosaic/00B2A35D018CED36

Supply 1, duration 0

**Comment by decentraliser** [comment]
@trestoJP is it still happening with the new release?

**Comment by trestoJP** [comment]
@decentraliser Yes, still happening with 0.8.12
I cant add it, like this. + key does not respond.
![ 2020-01-22 16-52-03-345](https://user-images.githubusercontent.com/59822825/72875432-9a555280-3d37-11ea-9d5d-eb3f3f8e27b4.png)

**Comment by decentraliser** [comment]
OK this should be fixed in 0.8.13, coming soon

**Comment by trestoJP** [comment]
This one still happening with 0.8.13
+ key does not respond again.
